name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Thay đổi nếu bạn sử dụng nhánh khác

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Thay đổi nếu bạn sử dụng phiên bản khác

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      run: npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
