name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Configure Git
      run: |
        git config --global user.email "nguyenkimthanh25122002@gmail.com"
        git config --global user.name "nthanh12"

    - name: Set remote URL
      run: git remote set-url origin https://${{ secrets.GHD_TOKEN }}@github.com/nthanh12/fe-teaching.git

    - name: Deploy
      env:
        GH_TOKEN: ${{ secrets.GHD_TOKEN }}
      run: npm run deploy
